### ISSUE TITLE
docs: Add more details for encrypting secrets

### ISSUE THREAD

**Issue by pnadolny13** [meltano/cloud-docs#10]
I was attempting to add new encrypted secrets to the squared project and it would be helpful to have more detailed docs on how to do this, especially because I'm extra sensitive to making sure this is right to avoid exposing secrets or breaking pipelines accidentally. I saw [these docs](https://github.com/meltano/cloud-docs/blob/main/docs/onboarding.md#step-2-encrypt-and-submit-the-env-file). Things that could be helpful:

- should I install the kms-ext in my meltano project (like in Squared) or just run via command line
- full how-to guide with commands and what the expected output should be. All keys were updated in my diff is that expected or not?
- can I decrypt my updated encrypted secrets to check everything worked before commiting? Or how can I know it worked?
- limitations of kms tool - i.e. my tap-google-analytics env var isnt supported

cc @magreenbaum

**Comment by magreenbaum** [comment]
Thanks for raising @pnadolny13. I will write up a PR to add these items.

**Comment by magreenbaum** [comment]
@pnadolny13 I'm not familiar with the `tap-google-analytics` env var limitation. Could you provide me some context just so I understand what's going on?

**Comment by pnadolny13** [comment]
>@pnadolny13 I'm not familiar with the tap-google-analytics env var limitation. Could you provide me some context just so I understand what's going on?

@magreenbaum I couldnt find the reference but I remember someone saying that we couldnt support the google credentials as an environment variable because its too long. There was a suggested feature somewhere where we could split the input into multiple parts that are each individually encrypted then when we decrypt we know how to put them back together.
