### ISSUE TITLE
Update Docs on Feature Roadmap Plans 

### ISSUE THREAD

**Issue by magreenbaum** [meltano/cloud-docs#11]
And some very basic infra info. 
Where is meltano cloud hosted? What region?

**Comment by aaronsteers** [comment]
@magreenbaum - Thanks for logging. If we can, I think it would be good to log these:

1. We use AWS.
2. Our primary AWS region today is ___.

And documenting these are to-come:

1. We plan to add a static source IP for IP whitelisting, early in Beta.
2. We plan to add EU regions (timing TBD).

This gives customers the minimal information they would need for planning, but doesn't go deep into implementation details which might be considered trade secrets or might change in future.

**Comment by aaronsteers** [comment]
Logged related to follow up on the EU region question:

- https://github.com/meltano/infra/issues/295
