### ISSUE TITLE
Document `meltano cloud` CLI here in `cloud-docs`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/cloud-docs#18]
As suggested by @cjohnhanson, we should have a place to document Cloud CLI patterns.

We can add docs to the `meltano/meltano` repo, but those will not automatically be published to docs.meltano.com until the changes merge to `main`. This `cloud-docs` repo is a good place to put Cloud CLI docs and usage examples.

Optionally, we can _also_ link over to additional markdown docs in the `meltano/meltano` repo itself, pinning our URL refs to the `cloud` branch in that case.

**Comment by tayloramurphy** [comment]
We're going to just move everything into the main cloud docs. We should likely pull the Cloud CLI docs in the main branch at this point.
